blocedpackets:
  PacketPlayInWindowClick:
    limit: 300
    normal: 200
    cancel: false
  PacketPlayInUseEntity:
    limit: 300
    normal: 200
    cancel: true
  PacketPlayInEntityAction:
    limit: 150
    normal: 100
    cancel: true
  PacketPlayInUpdateSign:
    limit: 3
    normal: 2
    cancel: false
  PacketPlayInTabComplete:
    limit: 25
    normal: 20
    cancel: false
  PacketPlayInFlying:
    limit: 770
    normal: 670
    cancel: true
  PacketPlayInPositionLook:
    limit: 770
    normal: 43
    cancel: true
  PacketPlayInLook:
    limit: 60
    normal: 16
    cancel: true
  PacketPlayInArmAnimation:
    limit: 35
    normal: 30
    cancel: true
  PacketPlayInBlockDig:
    limit: 700
    normal: 24
    cancel: true
  PacketPlayInBlockPlace:
    limit: 50
    normal: 40
    cancel: true
  PacketPlayInChat:
    limit: 4
    normal: 3
    cancel: false
  PacketPlayInSettings:
    limit: 10
    normal: 5
    cancel: false
  PacketPlayInAbilities:
    limit: 70
    normal: 60
    cancel: false
  PacketPlayInCustomPayload:
    limit: 10
    normal: 3
    cancel: false
settings:
  maxAccountsPerIp: 2
  instantPerm: true
  globalPacketLimit: 800
  normalPacketsSend: 150
licence: 0x00000000000000000001
nbt:
  EntityTagSize: 500
messages:
  kick: '&cWykryto atak typu exploit!'
  tooMuchIp: '&cPrzynajmniej 2 klientow o tym samym adresie ip znajduja sie na serwerze!'
  wdlDetected: '&cWykryto u ciebie klienta world downloader!'
  reload: '&cSerwer jest przeladowywany lub wylaczony!'
penalty:
  - 'ban-ip %ip%'
  - 'ban %nick%'
